baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'BTS Idrett | StudentIdrettslaget på Høgskulen på Vestlandet Bergen'
tags = ["sports", "students", "community"]
config = "config.toml"
theme = "osprey"
canonifyURLS = true
disqusShortname = "btsi"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline1 = "BTS Idrett"
  tagline2 = "Studentidrettslaget ved HVL Bergen"
  author = "friByte"
  description = "BTSI er studentidrettsforeningen på Høgskulen på Vestlandet nærregion Bergen."
  logoBig = "/img/btsilogo_farget.png"
  logoSmall = "/img/btsilogo_hvit.png"
  favicon = "/img/favicon-32x32.png"
  opengraphImage = "/img/btsilogo_farget.png"
  email = ""
  googleTagManager = ""
  customCSS = false

  # Social media links in footer
  facebook = "BTS.Idrettslag"
  instagram = "btsidrett"

  # Copyright and theme author credit in footer
  copyright = false
  credit = true

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = true
  cacheBustJS = true

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = "https://usebasin.com/f/0eae7044d4c2"

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "Informasjon"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Våre Idrettslag"
  url  = "/#work"
  weight = 2
[[menu.main]]
  name = "Kontakt"
  url  = "/#contact"
  weight = 3